#!/bin/bash

### BEGIN INIT INFO
# Provides:          caddy
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: caddy
# Description:       Caddy Go Web server
### END INIT INFO

/sbin/runuser hinst -s /bin/bash -c "/bin/bash /home/hinst/ufd/App/caddy/assuming-control.sh $1"
